[tox]
envlist =
    py{3.13,3.14}-sphinx{8.1,9.0,9.1}-tests
    py{3.13,3.14}-sphinx{8.1,9.0,9.1}-docs-html
    py{3.13,3.14}-sphinx{8.1,9.0,9.1}-docs-text

[testenv]
changedir = {toxinidir}
package = editable
extras =
    tests: test
    docs: docs
deps =
    sphinx8.1: Sphinx>=8.1,<8.2
    sphinx9.0: Sphinx>=9.0,<9.1
    sphinx9.1: Sphinx>=9.1,<9.2
commands =
    tests: python -m pytest tests
    docs-html: python -m sphinx -E -b html docs {envtmpdir}/authorguide-html --fail-on-warning
    docs-text: python -m sphinx -E -b text docs {envtmpdir}/authorguide-text --fail-on-warning
